### ISSUE TITLE
Fix example on README

### ISSUE THREAD

**Issue by adriaPerez** [skyrpex/query-syntax-php#6]
The current example has a couple of syntax errors:

Here, the `query` variable should be changed to `$query` (add the missing `$`).
https://github.com/skyrpex/query-syntax-php/blame/master/README.md#L14

The same happens here with `lexer`.
https://github.com/skyrpex/query-syntax-php/blame/master/README.md#L14

**Comment by skyrpex** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by skyrpex** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.
